// <auto-generated />
using Hotel_Management_Software.DataAccess.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hotel_Management_Software.DataAccess.Migrations
{
    [DbContext(typeof(ContextDB))]
    [Migration("20240206211101_edited_hotel_entity_removed_column")]
    partial class edited_hotel_entity_removed_column
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hotel_Management_Software.DataAccess.Entities.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HotelId"));

                    b.Property<string>("HotelEmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HotelLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HotelPasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("HotelPicture")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("HotelTelephoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LoginNumber")
                        .HasColumnType("integer");

                    b.HasKey("HotelId");

                    b.ToTable("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
