name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    name: Deploy
    uses: ./.github/workflows/docker-publish.yml
    secrets: inherit

  update-db:
    needs: build
    name: Apply migrations
    uses: ./.github/workflows/update-db.yml
    secrets: inherit
